config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'
  # get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :koalas

  get 'admin' => 'admin#index'

  get 'signup' => 'users#new'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'passwords/request', to: 'passwords#request_form'
  get 'passwords/resetform', to: 'passwords#reset_form'
  post 'passwords/forgot', to: 'passwords#forgot', as: :password_forgot
  post 'passwords/reset', to: 'passwords#reset'

  root 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/koala.rb
class Koala < ApplicationRecord
end

app/controllers/koalas_controller.rb
class KoalasController < ApplicationController
  before_action :set_koala, only: [:show, :edit, :update, :destroy]

  # GET /koalas
  # GET /koalas.json
  def index
    @koalas = Koala.all
  end

  # GET /koalas/1
  # GET /koalas/1.json
  def show
  end

  # GET /koalas/new
  def new
    @koala = Koala.new
  end

  # GET /koalas/1/edit
  def edit
  end

  # POST /koalas
  # POST /koalas.json
  def create
    @koala = Koala.new(koala_params)

    respond_to do |format|
      if @koala.save
        format.html { redirect_to @koala, notice: 'Koala was successfully created.' }
        format.json { render :show, status: :created, location: @koala }
      else
        format.html { render :new }
        format.json { render json: @koala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /koalas/1
  # PATCH/PUT /koalas/1.json
  def update
    respond_to do |format|
      if @koala.update(koala_params)
        format.html { redirect_to @koala, notice: 'Koala was successfully updated.' }
        format.json { render :show, status: :ok, location: @koala }
      else
        format.html { render :edit }
        format.json { render json: @koala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /koalas/1
  # DELETE /koalas/1.json
  def destroy
    @koala.destroy
    respond_to do |format|
      format.html { redirect_to koalas_url, notice: 'Koala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koala
      @koala = Koala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def koala_params
      params.require(:koala).permit(:name, :dob, :colour, :character, :favourite_food)
    end
end

app/helpers/koalas_helper.rb
module KoalasHelper
end

app/views/koalas/_form.html.erb
<%= form_with(model: koala, local: true) do |form| %>
  <% if koala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(koala.errors.count, "error") %> prohibited this koala from being saved:</h2>

      <ul>
      <% koala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :character %>
    <%= form.text_field :character %>
  </div>

  <div class="field">
    <%= form.label :favourite_food %>
    <%= form.text_field :favourite_food %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/koalas/edit.html.erb
<h1>Editing Koala</h1>

<%= render 'form', koala: @koala %>

<%= link_to 'Show', @koala %> |
<%= link_to 'Back', koalas_path %>

app/views/koalas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Koalas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Colour</th>
      <th>Character</th>
      <th>Favourite food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @koalas.each do |koala| %>
      <tr>
        <td><%= koala.name %></td>
        <td><%= koala.dob %></td>
        <td><%= koala.colour %></td>
        <td><%= koala.character %></td>
        <td><%= koala.favourite_food %></td>
        <td><%= link_to 'Show', koala %></td>
        <td><%= link_to 'Edit', edit_koala_path(koala) %></td>
        <td><%= link_to 'Destroy', koala, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Koala', new_koala_path %>

app/views/koalas/new.html.erb
<h1>New Koala</h1>

<%= render 'form', koala: @koala %>

<%= link_to 'Back', koalas_path %>

app/views/koalas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @koala.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @koala.dob %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @koala.colour %>
</p>

<p>
  <strong>Character:</strong>
  <%= @koala.character %>
</p>

<p>
  <strong>Favourite food:</strong>
  <%= @koala.favourite_food %>
</p>

<%= link_to 'Edit', edit_koala_path(@koala) %> |
<%= link_to 'Back', koalas_path %>